const UpdateUserDetailsActionsConstants = {
    UPDATE_NEW_USERNAME: 'UPDATE_NEW_USERNAME',
    UPDATE_NEW_LOCATION: 'UPDATE_NEW_LOCATION',
    UPDATE_NEW_PASSWORD: 'UPDATE_NEW_PASSWORD',
    SUBMIT_NEW_DETAILS: 'SUBMIT_NEW_DETAILS',
    SUBMIT_NEW_DETAILS_SUCCESS: 'SUBMIT_NEW_DETAILS_SUCCESS',
    SUBMIT_NEW_DETAILS_FAIL: 'SUBMIT_NEW_DETAILS_FAIL',
};

export { UpdateUserDetailsActionsConstants }
