const UpdateUserDetailsActionsConstants = {
    UPDATE_NEW_USERNAME: 'UPDATE_NEW_USERNAME',
    UPDATE_NEW_LOCATION: 'UPDATE_NEW_LOCATION',
    UPDATE_NEW_PASSWORD: 'UPDATE_NEW_PASSWORD',
    SUBMIT_NEW_DETAILS: 'SUBMIT_NEW_DETAILS',
    SUBMIT_NEW_DETAILS_SUCCESS: 'SUBMIT_NEW_DETAILS_SUCCESS',
    SUBMIT_NEW_DETAILS_FAIL: 'SUBMIT_NEW_DETAILS_FAIL',
    UPDATE_USER_COORDS: 'UPDATE_USER_COORDS',
    LOAD_LOCATIONS: 'UP_U_D_LOAD_LOCATIONS',
    COMPLETE_LOAD_LOCATIONS: 'UP_U_D_COMPLETE_LOAD_LOCATIONS',
    UPDATE_SUGGESTION: 'UP_U_D_UPDATE_SUGGESTION',
    UPDATE_LOC: 'UP_U_D_UPDATE_LOC'
};

export { UpdateUserDetailsActionsConstants }
