const SearchEngineActionsConstants = {
    UPDATE_TAG: 'UPDATE_TAG',
    LOAD_TAGS: 'LOAD_TAGS',
    LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS',
    LOAD_TAGS_FAILURE: 'LOAD_TAGS_FAILURE',
    UPDATE_NAME: 'UPDATE_NAME',
    ADVANCED_OPEN: 'ADVANCED_OPEN',
    ADVANCED_CLOSE: 'ADVANCED_CLOSE',
    UPDATE_RATING: 'UPDATE_RATING',
    UPDATE_CLOSER_BETTER: 'UPDATE_CLOSER_BETTER'
};

export { SearchEngineActionsConstants }
