const SearchEngineActionsConstants = {
    UPDATE_TAG: 'UPDATE_TAG',
    LOAD_TAGS: 'LOAD_TAGS',
    LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS',
    LOAD_TAGS_FAILURE: 'LOAD_TAGS_FAILURE',
    UPDATE_NAME: 'UPDATE_NAME',
    ADVANCED_OPEN: 'ADVANCED_OPEN',
    ADVANCED_CLOSE: 'ADVANCED_CLOSE',
    UPDATE_RATING: 'UPDATE_RATING',
    UPDATE_CLOSER_BETTER: 'UPDATE_CLOSER_BETTER',
    VIEW_MAP_SET:'VIEW_MAP_SET',
    VIEW_MAP_UNSET: 'VIEW_MAP_UNSET',
    LOAD_LOCATIONS: 'LOAD_LOCATIONS',
    COMPLETE_LOAD_LOCATIONS: 'COMPLETE_LOAD_LOCATIONS',
    UPDATE_SUGGESTION: 'UPDATE_SUGGESTION',
    UPDATE_LOC: 'UPDATE_LOC'
};

export { SearchEngineActionsConstants }
