const LoginActionsConstants = {
    UPDATE_TAG: 'UPDATE_TAG',
    LOAD_TAGS: 'LOAD_TAGS',
    LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS',
    LOAD_TAGS_FAILURE: 'LOAD_TAGS_FAILURE',
    USERNAME_UPDATE: 'USERNAME_UPDATE',
    PASSWORD_UPDATE: 'PASSWORD_UPDATE',
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    LOAD_LOGIN: 'LOAD_LOGIN'
};

export { LoginActionsConstants }
