const LoginActionsConstants = {
    USERNAME_UPDATE: 'USERNAME_UPDATE',
    PASSWORD_UPDATE: 'PASSWORD_UPDATE',
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    LOAD_USER: 'LOAD_USER',
    DISCONNECT: 'DISCONNECT',
    SET_NEW_USERNAME: 'SET_NEW_USERNAME',
    SET_SIGNUP_LOGIN : 'SET_SIGNUP_LOGIN',
    UPDATE_USER_COORDS: 'SIGNUP_UPDATE_USER_COORDS',
    LOAD_LOCATIONS: 'SIGNUP_LOAD_LOCATIONS',
    COMPLETE_LOAD_LOCATIONS: 'SIGNUP_COMPLETE_LOAD_LOCATIONS',
    UPDATE_SUGGESTION: 'SIGNUP_UPDATE_SUGGESTION',
    UPDATE_LOC: 'SIGNUP_UPDATE_LOC',
};

export { LoginActionsConstants }
