const SubmitRestActionsConstants = {
    UPDATE_REST_NAME: 'UPDATE_REST_NAME',
    UPDATE_REST_LOCATION: 'UPDATE_REST_LOCATION',
    UPDATE_REST_DESCRIPTION: 'UPDATE_REST_DESCRIPTION',
    SUBMIT_NEW_REST: 'SUBMIT_NEW_REST',
    SUBMIT_NEW_REST_SUCCESS: 'SUBMIT_NEW_REST_SUCCESS',
    SUBMIT_NEW_REST_FAIL: 'SUBMIT_NEW_REST_FAIL',
    UPDATE_REST_COORDS: 'UPDATE_REST_COORDS'
};

export { SubmitRestActionsConstants }
