const RestSearchActionsConstants = {
  CLONE_ACTION: 'CLONE_ACTION',
  APPLY_FILTER_ACTION: 'APPLY_FILTER_ACTION',
  OPEN_LIGHT_BOX_ACTION: 'OPEN_LIGHT_BOX_ACTION',
  DELETE_ACTION: 'DELETE_ACTION',
  LOAD_IMAGES_ACTION: 'LOAD_IMAGES_ACTION',
  LOAD_IMAGES_ACTION_SUCCESS: 'LOAD_IMAGES_ACTION_SUCCESS',
  LOAD_IMAGES_ACTION_FAILURE: 'LOAD_IMAGES_ACTION_FAILURE',
  SET_ACTIVE_IMAGE: 'SET_ACTIVE_IMAGE',
  UNSET_ACTIVE_IMAGE: 'UNSET_ACTIVE_IMAGE',
  UPDATE_GALLERY_WIDTH: 'UPDATE_GALLERY_WIDTH',
  //TODO DELETE ALL THE ABOVE
  GO_TO_REST_ACTION: 'GO_TO_REST_ACTION',
  LOAD_RESTS_ACTION: 'LOAD_RESTS_ACTION',
  LOAD_RESTS_ACTION_SUCCESS: 'LOAD_RESTS_ACTION_SUCCESS',
  LOAD_RESTS_ACTION_FAILURE: 'LOAD_RESTS_ACTION_FAILURE'

};

export { RestSearchActionsConstants };
