const RestSearchActionsConstants = {

  GO_TO_REST_ACTION: 'GO_TO_REST_ACTION',
  LOAD_RESTS_ACTION: 'LOAD_RESTS_ACTION',
  LOAD_RESTS_ACTION_SUCCESS: 'LOAD_RESTS_ACTION_SUCCESS',
  LOAD_RESTS_ACTION_FAILURE: 'LOAD_RESTS_ACTION_FAILURE'

};

export { RestSearchActionsConstants };
