const UserSearchActionsConstants = {
    USER_SEARCH_QUERY: 'USER_SEARCH_QUERY',
    USER_SEARCH_QUERY_SUCCESS: 'USER_SEARCH_QUERY_SUCCESS',
    USER_SEARCH_QUERY_FAIL: 'USER_SEARCH_QUERY_FAIL'

};

export { UserSearchActionsConstants }
