const UserPageActionsConstants = {
    LOAD_USER_INFO: 'LOAD_USER_INFO',
    LOAD_USER_INFO_SUCCSESS: 'LOAD_USER_INFO_SUCCSESS',
    LOAD_USER_INFO_FAIL: 'LOAD_USER_INFO_FAIL',
    DELETE_USER_REVIEW: 'DELETE_USER_REVIEW',
    DELETE_USER_REVIEW_SUCCSESS: 'DELETE_USER_REVIEW_SUCCSESS',
    DELETE_USER_REVIEW_FAIL: 'DELETE_USER_REVIEW_SUCCSESS'
};

export { UserPageActionsConstants }
