const UserPageActionsConstants = {
    LOAD_USER_INFO: 'LOAD_USER_INFO',
    LOAD_USER_INFO_SUCCSESS: 'LOAD_USER_INFO_SUCCSESS',
    LOAD_USER_INFO_FAIL: 'LOAD_USER_INFO_FAIL',
    DELETE_USER_REVIEW: 'DELETE_USER_REVIEW',
    DELETE_USER_REVIEW_SUCCSESS: 'DELETE_USER_REVIEW_SUCCSESS',
    DELETE_USER_REVIEW_FAIL: 'DELETE_USER_REVIEW_SUCCSESS',
    UPLOAD_REQUEST:  'UPLOAD_REQUEST',
    UPLOAD_PROGRESS: 'UPLOAD_PROGRESS',
    UPLOAD_SUCCESS:  'UPLOAD_SUCCESS',
    UPLOAD_FAILURE:  'UPLOAD_FAILURE',
    UPDATE_FILE: 'UPDATE_FILE'
};

export { UserPageActionsConstants }
