const RestPageActionsConstants = {
    LOAD_REST_INFO: 'LOAD_REST_INFO',
    LOAD_REST_INFO_SUCCSESS: 'LOAD_REST_INFO_SUCCSESS',
    LOAD_REST_INFO_FAIL: 'LOAD_REST_INFO_FAIL',
    DELETE_REST_REVIEW: 'DELETE_REST_REVIEW',
    DELETE_REST_REVIEW_SUCCSESS: 'DELETE_REST_REVIEW_SUCCSESS',
    DELETE_REST_REVIEW_FAIL: 'DELETE_REST_REVIEW_SUCCSESS',

};

export { RestPageActionsConstants }
